# https://travis-ci.org/tornadoweb/tornado
dist: trusty

# Use containers instead of full VMs for faster startup.
sudo: false

language: python

matrix:
    fast_finish: true
    include:
      - python: 2.7
        install:
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' incremental==16.10.1
          - travis_retry pip install  --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' mock monotonic singledispatch Twisted pycurl
          - travis_retry python setup.py install
          - travis_retry pip install  --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' virtualenv
        script:
          - export TARGET="-m tornado.test.runtests"
          - unset TORNADO_EXTENSION && python -m tornado.test
          - python $TARGET --ioloop=tornado.platform.select.SelectIOLoop
          - python $TARGET --httpclient=tornado.curl_httpclient.CurlAsyncHTTPClient
          - python $TARGET --ioloop=tornado.platform.twisted.TwistedIOLoop
          - python $TARGET --resolver=tornado.platform.twisted.TwistedResolver
          - python $TARGET --ioloop=tornado.ioloop.PollIOLoop --ioloop_time_monotonic

      - python: pypy2.7-5.8.0
        install:
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' backports_abc singledispatch futures
        #   - travis_retry pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' mock
          - travis_retry python setup.py install
        script:
          - unset TORNADO_EXTENSION && python -m tornado.test

      - python: 3.4
        install:
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' backports_abc
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' incremental==16.10.1
          - travis_retry pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' pycurl Twisted
          - travis_retry python setup.py install
        script:
          - unset TORNADO_EXTENSION && python -m tornado.test

      - python: 3.5
        install:
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' incremental==16.10.1
          - travis_retry pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' pycurl Twisted
          - travis_retry python setup.py install
        script:
          - export TARGET="-m tornado.test.runtests"
          - unset TORNADO_EXTENSION && python -m tornado.test
          - python -bb $TARGET

      - python: 3.6
        install:
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' incremental==16.10.1
          - travis_retry pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' setuptools==45
          - travis_retry pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' dataclasses
          - travis_retry pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' pycurl Twisted
          - travis_retry python setup.py install
        script:
          - export TARGET="-m tornado.test.runtests"
          - unset TORNADO_EXTENSION && python -m tornado.test
          - python -bb $TARGET
        #   - cd docs && mkdir sphinx-out && sphinx-build -E -n -W -b html . sphinx-out
        #   - cd docs && mkdir sphinx-doctest-out && sphinx-build -E -n -b doctest . sphinx-out
        #   - cd .. && flake8

      - python: nightly
        install:
          - travis_retry pip install --index-url 'https://:2018-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' -U setuptools
          - travis_retry python setup.py install
        script:
          - unset TORNADO_EXTENSION && python -m tornado.test

      - python: pypy3.5-5.8.0
        install:
          - pip install --index-url 'https://:2024-09-16T19:22:58.819187Z@time-machines-pypi.sealsecurity.io/' backports_abc singledispatch
          - travis_retry python setup.py install
        script:
          - unset TORNADO_EXTENSION && python -m tornado.test
          - python -m tornado.test.runtests
